### ISSUE TITLE
Error on Make

### ISSUE THREAD

**Issue by nxfxcom** [ZerBea/hcxbtdumptool#2]
Hello,

When running make on a Pi4 with Kali I get the following error:

`make
cc -O3 -Wall -Wextra -std=gnu99  -o hcxbtdumptool hcxbtdumptool.c  -lbluetooth -lcrypto -lssl -DVERSION_TAG=\"0.0.1-32-g82b7d4e\" -DVERSION_YEAR=\"2020\"
hcxbtdumptool.c: In function ‘blescanloop’:
hcxbtdumptool.c:108:15: error: ‘FDUSECTIMER’ undeclared (first use in this function)
  108 | tvfd.tv_sec = FDUSECTIMER;
      |               ^~~~~~~~~~~
hcxbtdumptool.c:108:15: note: each undeclared identifier is reported only once for each function it appears in
At top level:
hcxbtdumptool.c:69:13: warning: ‘blescanloop’ defined but not used [-Wunused-function]
   69 | static void blescanloop()
      |             ^~~~~~~~~~~
hcxbtdumptool.c:39:22: warning: ‘ble’ defined but not used [-Wunused-variable]
   39 | static unsigned char ble[HCI_MAX_FRAME_SIZE +2];
      |                      ^~~
make: *** [Makefile:31: build] Error 1`

Did some googling but had no luck!

Thank you

**Comment by ZerBea** [comment]
Ok, it's a playground and not really ready for production. Pushed an update so that you can compile it, now. The two remaining warnings are ok. The vars are defined, but not in use, yet. There is still a lot of work todo on this tool.
